import { QuizSorusu } from './quizTypes'

export const QUIZ_SORULARI: QuizSorusu[] = [
  // ── BÖLÜM 1: KİŞİSEL PROFİL ──
  {
    id: 'hane_tipi',
    bolum: 'Kişisel Profil',
    soru: 'Hangi yaşam durumunuzu tanımlıyor?',
    ikon: '👤',
    secenekler: [
      { label: 'Yalnız yaşıyorum', value: 'yalniz',
        agirlik: { imkanlar: 1.3, kultur: 1.2 } },
      { label: 'Çift, çocuksuz', value: 'cift',
        agirlik: { imkanlar: 1.2, ulasim: 1.1 } },
      { label: 'Çocuklu aile', value: 'aileli',
        agirlik: { egitim: 1.5, guvenlik: 1.4, yesil_alan: 1.2 } },
      { label: 'Yaşlı/emekli', value: 'emekli',
        agirlik: { saglik: 1.5, guvenlik: 1.3, ulasim: 1.2 } },
      { label: 'Öğrenci', value: 'ogrenci',
        agirlik: { ulasim: 1.4, yasam_maliyeti: 1.5, imkanlar: 1.2 } },
    ],
  },
  {
    id: 'yas_grubu',
    bolum: 'Kişisel Profil',
    soru: 'Yaş grubunuz?',
    ikon: '🎂',
    secenekler: [
      { label: '18-25', value: 'genc',
        agirlik: { imkanlar: 1.3, ulasim: 1.2, yasam_maliyeti: 1.3 } },
      { label: '26-35', value: 'genc_yetiskin',
        agirlik: { ulasim: 1.2, imkanlar: 1.1 } },
      { label: '36-50', value: 'orta',
        agirlik: { egitim: 1.2, guvenlik: 1.2 } },
      { label: '50+', value: 'olgun',
        agirlik: { saglik: 1.4, guvenlik: 1.3, yesil_alan: 1.2 } },
    ],
  },

  // ── BÖLÜM 2: ULAŞIM ──
  {
    id: 'ulasim_tercihi',
    bolum: 'Ulaşım',
    soru: 'Günlük ulaşımda ne kullanıyorsunuz?',
    ikon: '🚇',
    secenekler: [
      { label: 'Toplu taşıma (metro/otobüs)', value: 'toplu',
        agirlik: { ulasim: 1.5 } },
      { label: 'Özel araç', value: 'arac',
        agirlik: { ulasim: 0.8, yasam_maliyeti: 1.1 } },
      { label: 'Yürüyerek/bisikletle', value: 'yuru',
        agirlik: { yesil_alan: 1.2, imkanlar: 1.3 } },
      { label: 'Uzaktan çalışıyorum', value: 'uzak',
        agirlik: { ulasim: 0.6, yesil_alan: 1.2, guvenlik: 1.2 } },
    ],
  },
  {
    id: 'merkez_uzaklik',
    bolum: 'Ulaşım',
    soru: 'İstanbul merkezine yakınlık ne kadar önemli?',
    ikon: '📍',
    secenekler: [
      { label: 'Çok önemli, merkeze yakın olmalı', value: 'cok_onemli',
        agirlik: { ulasim: 1.4 } },
      { label: 'Önemli ama şart değil', value: 'onemli',
        agirlik: { ulasim: 1.2 } },
      { label: 'Fark etmez, konforlu ulaşım yeterli', value: 'farketmez',
        agirlik: { ulasim: 1.0 } },
      { label: 'Merkez dışı tercih ederim', value: 'dis',
        agirlik: { ulasim: 0.7, yesil_alan: 1.3, guvenlik: 1.2 } },
    ],
  },

  // ── BÖLÜM 3: GÜVENLİK ──
  {
    id: 'guvenlik_onceligi',
    bolum: 'Güvenlik',
    soru: 'Güvenlik konusundaki önceliğiniz?',
    ikon: '🛡️',
    secenekler: [
      { label: 'En yüksek önceliğim', value: 'cok_yuksek',
        agirlik: { guvenlik: 1.8 } },
      { label: 'Önemli bir faktör', value: 'onemli',
        agirlik: { guvenlik: 1.4 } },
      { label: 'Orta düzeyde önemli', value: 'orta',
        agirlik: { guvenlik: 1.1 } },
      { label: 'Diğer faktörler daha önemli', value: 'dusuk',
        agirlik: { guvenlik: 0.8 } },
    ],
  },
  {
    id: 'deprem',
    bolum: 'Güvenlik',
    soru: 'Deprem riski ne kadar önemli?',
    ikon: '🏔️',
    secenekler: [
      { label: 'Çok önemli, düşük riskli bölge şart', value: 'cok',
        agirlik: { deprem_skoru: 1.8 } },
      { label: 'Önemli bir faktör', value: 'onemli',
        agirlik: { deprem_skoru: 1.4 } },
      { label: 'Biraz önemli', value: 'biraz',
        agirlik: { deprem_skoru: 1.1 } },
      { label: 'Pek önemsemiyorum', value: 'az',
        agirlik: { deprem_skoru: 0.7 } },
    ],
  },

  // ── BÖLÜM 4: EĞİTİM & SAĞLIK ──
  {
    id: 'egitim',
    bolum: 'Eğitim & Sağlık',
    soru: 'Eğitim imkanları ne kadar önemli?',
    ikon: '📚',
    secenekler: [
      { label: 'Çok önemli (okul çağında çocuğum var)', value: 'cok',
        agirlik: { egitim: 1.8 } },
      { label: 'Önemli (ileride düşünüyorum)', value: 'onemli',
        agirlik: { egitim: 1.3 } },
      { label: 'Biraz önemli', value: 'biraz',
        agirlik: { egitim: 1.0 } },
      { label: 'Şu an önemli değil', value: 'az',
        agirlik: { egitim: 0.6 } },
    ],
  },
  {
    id: 'saglik',
    bolum: 'Eğitim & Sağlık',
    soru: 'Sağlık tesislerine erişim önceliğiniz?',
    ikon: '🏥',
    secenekler: [
      { label: 'Çok önemli, yakın hastane şart', value: 'cok',
        agirlik: { saglik: 1.8 } },
      { label: 'Önemli', value: 'onemli',
        agirlik: { saglik: 1.4 } },
      { label: 'Orta düzeyde', value: 'orta',
        agirlik: { saglik: 1.0 } },
      { label: 'Pek önemli değil', value: 'az',
        agirlik: { saglik: 0.7 } },
    ],
  },

  // ── BÖLÜM 5: YAŞAM KALİTESİ ──
  {
    id: 'sosyal_hayat',
    bolum: 'Yaşam Kalitesi',
    soru: 'Sosyal hayat beklentiniz?',
    ikon: '🍽️',
    secenekler: [
      { label: 'Canlı, restoran/kafe yoğun semt', value: 'cok_aktif',
        agirlik: { imkanlar: 1.6, kultur: 1.3 } },
      { label: 'Dengeli, yeterli imkan olsun', value: 'dengeli',
        agirlik: { imkanlar: 1.2 } },
      { label: 'Sakin, az kalabalık tercih ederim', value: 'sakin',
        agirlik: { imkanlar: 0.8, yesil_alan: 1.3, guvenlik: 1.2 } },
      { label: 'Fark etmez', value: 'farketmez',
        agirlik: { imkanlar: 1.0 } },
    ],
  },
  {
    id: 'yesil_alan',
    bolum: 'Yaşam Kalitesi',
    soru: 'Doğa ve yeşil alan ne kadar önemli?',
    ikon: '🌳',
    secenekler: [
      { label: 'Çok önemli, park/sahil yakın olmalı', value: 'cok',
        agirlik: { yesil_alan: 1.8 } },
      { label: 'Önemli', value: 'onemli',
        agirlik: { yesil_alan: 1.4 } },
      { label: 'Biraz önemli', value: 'biraz',
        agirlik: { yesil_alan: 1.0 } },
      { label: 'Pek önemli değil', value: 'az',
        agirlik: { yesil_alan: 0.7 } },
    ],
  },
  {
    id: 'kultur',
    bolum: 'Yaşam Kalitesi',
    soru: 'Kültür & sanat hayatı önceliğiniz?',
    ikon: '🎭',
    secenekler: [
      { label: 'Çok önemli, müze/tiyatro yakın olmalı', value: 'cok',
        agirlik: { kultur: 1.8 } },
      { label: 'Önemli', value: 'onemli',
        agirlik: { kultur: 1.4 } },
      { label: 'Biraz önemli', value: 'biraz',
        agirlik: { kultur: 1.0 } },
      { label: 'Pek önemli değil', value: 'az',
        agirlik: { kultur: 0.6 } },
    ],
  },

  // ── BÖLÜM 6: BÜTÇE ──
  {
    id: 'kira_butce',
    bolum: 'Bütçe',
    soru: 'Aylık kira bütçeniz?',
    ikon: '💰',
    secenekler: [
      { label: '15.000 - 25.000 TL', value: 'dusuk',
        agirlik: { yasam_maliyeti: 1.8 }, kira_max: 25000 },
      { label: '25.000 - 40.000 TL', value: 'orta',
        agirlik: { yasam_maliyeti: 1.3 }, kira_max: 40000 },
      { label: '40.000 - 70.000 TL', value: 'yuksek',
        agirlik: { yasam_maliyeti: 1.0 }, kira_max: 70000 },
      { label: '70.000 TL+', value: 'lux',
        agirlik: { yasam_maliyeti: 0.6 }, kira_max: 200000 },
    ],
  },
  {
    id: 'yasam_maliyeti',
    bolum: 'Bütçe',
    soru: 'Yaşam maliyeti ne kadar belirleyici?',
    ikon: '📊',
    secenekler: [
      { label: 'En önemli faktörüm', value: 'cok',
        agirlik: { yasam_maliyeti: 1.8 } },
      { label: 'Önemli ama tek kriter değil', value: 'onemli',
        agirlik: { yasam_maliyeti: 1.3 } },
      { label: 'Orta düzeyde önemli', value: 'orta',
        agirlik: { yasam_maliyeti: 1.0 } },
      { label: 'Kalite önceliğim, maliyet ikincil', value: 'az',
        agirlik: { yasam_maliyeti: 0.6 } },
    ],
  },

  // ── BÖLÜM 7: ÖNCELİKLER ──
  {
    id: 'en_onemli',
    bolum: 'Öncelikler',
    soru: 'Sizi en iyi tanımlayan yaşam tarzı hangisi?',
    ikon: '⭐',
    secenekler: [
      { label: '🚇 Ulaşım odaklı — her yere kolay erişim', value: 'ulasim_odakli',
        agirlik: { ulasim: 1.5 } },
      { label: '🛡️ Güvenlik odaklı — huzurlu semt', value: 'guvenlik_odakli',
        agirlik: { guvenlik: 1.5 } },
      { label: '🎉 Sosyal odaklı — canlı mahalle', value: 'sosyal_odakli',
        agirlik: { imkanlar: 1.5, kultur: 1.3 } },
      { label: '🌳 Doğa odaklı — yeşil ve sakin', value: 'doga_odakli',
        agirlik: { yesil_alan: 1.5, guvenlik: 1.2 } },
      { label: '💰 Bütçe odaklı — uygun fiyat', value: 'butce_odakli',
        agirlik: { yasam_maliyeti: 1.6 } },
      { label: '📚 Aile odaklı — eğitim ve güvenlik', value: 'aile_odakli',
        agirlik: { egitim: 1.5, guvenlik: 1.4 } },
    ],
  },
  {
    id: 'semt_karakter',
    bolum: 'Öncelikler',
    soru: 'Hangi semt karakteri sizi en çok çekiyor?',
    ikon: '🏘️',
    secenekler: [
      { label: '🏙️ Modern, gelişmiş, kurumsal', value: 'modern',
        agirlik: { ulasim: 1.2, imkanlar: 1.2 } },
      { label: '🎨 Bohemyen, sanatsal, tarihi', value: 'bohemyen',
        agirlik: { kultur: 1.5, imkanlar: 1.2 } },
      { label: '🌿 Sakin, villalık, huzurlu', value: 'sakin',
        agirlik: { yesil_alan: 1.4, guvenlik: 1.3 } },
      { label: '🏘️ Geleneksel, komşuluk kültürü', value: 'geleneksel',
        agirlik: { guvenlik: 1.3, yasam_maliyeti: 1.2 } },
      { label: '🌊 Boğaz/deniz kenarı', value: 'deniz',
        agirlik: { yesil_alan: 1.3, imkanlar: 1.1 } },
    ],
  },
]
